### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/opt/miniircd/log/#webview.log'

### ISSUE THREAD

**Issue by stodge** [jrosdahl/miniircd#19]
I'm running miniircd as a Centos service, the script is run using:

/opt/miniircd/miniircd --setuid=nobody --logdir=/opt/miniircd/log --chroot=/opt/miniircd/jail --ports=6667

I can connect but when I try to join a room I get:

```
Traceback (most recent call last):
  File "/opt/miniircd/miniircd", line 931, in <module>
  File "/opt/miniircd/miniircd", line 926, in main
  File "/opt/miniircd/miniircd", line 783, in start
  File "/opt/miniircd/miniircd", line 549, in socket_readable_notification
  File "/opt/miniircd/miniircd", line 168, in __parse_read_buffer
  File "/opt/miniircd/miniircd", line 534, in __command_handler
  File "/opt/miniircd/miniircd", line 263, in join_handler
  File "/opt/miniircd/miniircd", line 601, in channel_log
IOError: [Errno 2] No such file or directory: '/opt/miniircd/log/#room_name.log'

```
The file exists:

ll opt/miniircd/log/
total 0
-rw-r--r-- 1 nobody nobody 0 May 18 18:55  #room_name.log

Am I missing anything? Thanks

**Comment by jrosdahl** [comment]
When using `--chroot`, `--logdir` refers to a directory inside the chroot jail, so you're probably missing a `/tmp/miniircd/jail/tmp/miniircd/log` directory.

**Comment by stodge** [comment]
Of course! Thanks!
