### ISSUE TITLE
Fatal Exception, possibly during disconnect?

### ISSUE THREAD

**Issue by rrodakowski** [jrosdahl/miniircd#30]
I'm running python 3.5.2. Here is what I was able to capture in the new log file option that was added with version 1.2.

2017-05-25 14:35:49,270 - miniircd[17155] - INFO - Accepted connection from 38.92.135.82:39133.
2017-05-25 14:35:54,580 - miniircd[17155] - INFO - Accepted connection from 198.179.137.227:12933.
2017-05-25 15:00:00,446 - miniircd[17155] - INFO - Accepted connection from 198.179.137.227:46866.
2017-05-25 15:00:27,807 - miniircd[17155] - INFO - Accepted connection from 38.92.135.82:35471.
2017-05-25 15:00:58,061 - miniircd[17155] - INFO - Disconnected connection from 38.92.135.82:39133 (ping timeout).
2017-05-25 15:00:58,062 - miniircd[17155] - ERROR - Fatal exception
Traceback (most recent call last):
  File "/opt/miniircd-1.2/miniircd", line 847, in start
    self.run(serversockets)
  File "/opt/miniircd-1.2/miniircd", line 913, in run
    for client in self.clients.values():
RuntimeError: dictionary changed size during iteration

**Comment by jrosdahl** [comment]
Thanks, looks like the Python 3 changes in #28 weren't quite enough.

**Comment by jrosdahl** [comment]
Fixed in 092d612cf9aad5b253c49b24abe5d3ad752b8b58.

**Comment by rrodakowski** [comment]
Thanks for making miniircd! We use it everyday!
