### ISSUE TITLE
pressing ctrl-c in a telnet connection causes fatal exception

### ISSUE THREAD

**Issue by rrodakowski** [jrosdahl/miniircd#32]
If I telnet to a minircd server, then press ctrl-c to exit telnet, the irc server will crash with a fatal exception. 

2017-08-02 14:31:59,048 - miniircd[22819] - ERROR - Fatal exception
Traceback (most recent call last):
  File "/opt/miniircd-1.2.1/miniircd", line 847, in start
    self.run(serversockets)
  File "/opt/miniircd-1.2.1/miniircd", line 884, in run
    self.clients[x].socket_readable_notification()
  File "/opt/miniircd-1.2.1/miniircd", line 596, in socket_readable_notification
    self.__readbuffer += socket_to_buffer(data)
  File "/opt/miniircd-1.2.1/miniircd", line 46, in socket_to_buffer
    return buf.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by rrodakowski** [comment]
Thanks.
