### ISSUE TITLE
Crash when editing the state file

### ISSUE THREAD

**Issue by JacenBoy** [jrosdahl/miniircd#49]
When performing an action that edits an existing state file (e.g. changing the topic when a topic already exists), the server crashes.

```
Traceback (most recent call last):
  File "miniircd", line 1250, in <module>
    main()
  File "miniircd", line 1241, in main
    server.start()
  File "miniircd", line 977, in start
    self.run(serversockets)
  File "miniircd", line 1019, in run
    self.clients[x].socket_readable_notification()
  File "miniircd", line 686, in socket_readable_notification
    self.__parse_read_buffer()
  File "miniircd", line 189, in __parse_read_buffer
    self.__handle_command(command, arguments)
  File "miniircd", line 668, in __command_handler
    handler_table[command]()
  File "miniircd", line 549, in topic_handler
    channel.topic = newtopic
  File "miniircd", line 76, in topic
    self._write_state()
  File "miniircd", line 111, in _write_state
    os.rename(path, self._state_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\Profile\\Documents\\Github\\miniircd\\state\\tmp5ur0mhvd' -> 'state/#test'
```

Tested on Windows 11 with Python 3.8.7.

**Comment by jrosdahl** [comment]
Fixed by #50.
