### ISSUE TITLE
unknown encoding: ascii in chroot

### ISSUE THREAD

**Issue by Hurgotron** [jrosdahl/miniircd#51]
If I start miniircd in a chroot environment, it crashes as soon as I try to connect:

```
./miniircd --setuid ircd:ircd --chroot=/var/chroot --channel-log-dir=/logs --motd=/motd.txt
Traceback (most recent call last):
  File "/home/ircd/miniircd-2.1/./miniircd", line 1251, in <module>
  File "/home/ircd/miniircd-2.1/./miniircd", line 1242, in main
  File "/home/ircd/miniircd-2.1/./miniircd", line 978, in start
  File "/home/ircd/miniircd-2.1/./miniircd", line 1020, in run
  File "/home/ircd/miniircd-2.1/./miniircd", line 687, in socket_readable_notification
  File "/home/ircd/miniircd-2.1/./miniircd", line 190, in __parse_read_buffer
  File "/home/ircd/miniircd-2.1/./miniircd", line 245, in __registration_handler
  File "/home/ircd/miniircd-2.1/./miniircd", line 774, in send_motd
  File "/home/ircd/miniircd-2.1/./miniircd", line 897, in get_motd_lines
LookupError: unknown encoding: ascii
```
Without motd file, the effect is similar:

```
Traceback (most recent call last):
  File "/home/ircd/miniircd-2.1/miniircd", line 1251, in <module>
  File "/home/ircd/miniircd-2.1/miniircd", line 1242, in main
  File "/home/ircd/miniircd-2.1/miniircd", line 978, in start
  File "/home/ircd/miniircd-2.1/miniircd", line 1020, in run
  File "/home/ircd/miniircd-2.1/miniircd", line 687, in socket_readable_notification
  File "/home/ircd/miniircd-2.1/miniircd", line 190, in __parse_read_buffer
  File "/home/ircd/miniircd-2.1/miniircd", line 669, in __command_handler
  File "/home/ircd/miniircd-2.1/miniircd", line 337, in join_handler
  File "/home/ircd/miniircd-2.1/miniircd", line 281, in __send_names
  File "/home/ircd/miniircd-2.1/miniircd", line 752, in channel_log
LookupError: unknown encoding: ascii
```
Without chroot, everything seems to work fine.

**Comment by Hurgotron** [comment]
I'm running Python 3.9.2-1 on Debian 11.1 (to be exact. Devuan Chimaera, but that should not matter).

strace tells me that my Python tries to load _bootlocale.py after chroot. I guess your Python 3.10 does not try to load it because it has been removed in that version, see https://github.com/pyinstaller/pyinstaller/issues/5693

Any suggestions?

**Comment by jrosdahl** [comment]
No other suggestions, sorry.
